# Generated by Django 4.2.4 on 2023-09-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aemail', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
