# Generated by Django 4.2.4 on 2023-09-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=30)),
                ('oname', models.CharField(max_length=30)),
                ('ocategory', models.CharField(max_length=30)),
                ('odescription', models.CharField(max_length=30)),
                ('oprice', models.FloatField(max_length=30)),
                ('oquantity', models.IntegerField(max_length=30)),
                ('obill', models.FloatField(max_length=30)),
                ('opurchasedate', models.DateTimeField(max_length=30)),
            ],
        ),
    ]
